version: '3.8'

services:
  visit-service:
    build: ./visit-service
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - rabbitmq

  notification-service:
    build: ./notification-service
    depends_on:
      - rabbitmq

  redis:
    image: redis:6.2

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"